export const products = [
  {
    id: 1,
    title: "Laptop 3",
    price: 1800,
    description: "Gaming laptop with RTX",
    category: "laptop",
    image: "/images/laptop/laptop3.jpg",
  },
  {
    id: 2,
    title: "Mobile 4",
    price: 750,
    description: "Phone with great camera",
    category: "mobile",
    image: "/images/mobile/mobile4.jpg",
    isBestSeller: true,
  },
  {
    id: 3,
    title: "Mobile 3",
    price: 600,
    description: "Affordable phone",
    category: "mobile",
    image: "/images/mobile/mobile3.jpg",
    isBestSeller: true,
  },
  {
    id: 4,
    title: "Headphone 10",
    price: 210,
    description: "Studio quality",
    category: "headphone",
    image: "/images/headphone/headphone10.jpg",
  },
  {
    id: 5,
    title: "Headphone 10",
    price: 210,
    description: "Studio quality",
    category: "headphone",
    image: "/images/headphone/headphone10.jpg",
  },
  {
    id: 6,
    title: "Laptop 1",
    price: 1500,
    description: "High performance laptop",
    category: "laptop",
    image: "/images/laptop/laptop1.jpg",
    isBestSeller: true,
  },
  {
    id: 7,
    title: "Laptop 2",
    price: 1200,
    description: "Portable and powerful",
    category: "laptop",
    image: "/images/laptop/laptop2.jpg",
    isBestSeller: true,
  },
  {
    id: 8,
    title: "Mobile 8",
    price: 720,
    description: "Phone with long battery",
    category: "mobile",
    image: "/images/mobile/mobile8.jpg",
    isBestSeller: true,
  },
  {
    id: 9,
    title: "Game 7",
    price: 45,
    description: "Casual game",
    category: "game",
    image: "/images/game/game7.jpg",
  },
  {
    id: 10,
    title: "Headphone 7",
    price: 170,
    description: "Over-ear premium",
    category: "headphone",
    image: "/images/headphone/headphone7.jpg",
  },
  {
    id: 11,
    title: "Laptop 5",
    price: 2000,
    description: "Premium ultrabook",
    category: "laptop",
    image: "/images/laptop/laptop5.jpg",
  },
  {
    id: 12,
    title: "Headphone 8",
    price: 110,
    description: "Good bass",
    category: "headphone",
    image: "/images/headphone/headphone8.jpg",
  },
  {
    id: 13,
    title: "Game 10",
    price: 50,
    description: "Indie game",
    category: "game",
    image: "/images/game/game10.jpg",
  },
];
