// Scripts/extendedProducts.mjs
// 60 محصول برای تمام دسته‌بندی‌ها

export const extendedProducts = [
  // لپتاپ‌ها (15 محصول)
  { id: 1, title: "Laptop 3", price: 1800, description: "Gaming laptop with RTX", category: "laptop", image: "/images/laptop/laptop3.jpg" },
  { id: 2, title: "Mobile 4", price: 750, description: "Phone with great camera", category: "mobile", image: "/images/mobile/mobile4.jpg", isBestSeller: true },
  { id: 3, title: "Mobile 3", price: 600, description: "Affordable phone", category: "mobile", image: "/images/mobile/mobile3.jpg", isBestSeller: true },
  { id: 4, title: "Headphone 10", price: 210, description: "Studio quality", category: "headphone", image: "/images/headphone/headphone10.jpg" },
  { id: 5, title: "Headphone 10", price: 210, description: "Studio quality", category: "headphone", image: "/images/headphone/headphone10.jpg" },
  { id: 6, title: "Laptop 1", price: 1500, description: "High performance laptop", category: "laptop", image: "/images/laptop/laptop1.jpg", isBestSeller: true },
  { id: 7, title: "Laptop 2", price: 1200, description: "Portable and powerful", category: "laptop", image: "/images/laptop/laptop2.jpg", isBestSeller: true },
  { id: 8, title: "Mobile 8", price: 720, description: "Phone with long battery", category: "mobile", image: "/images/mobile/mobile8.jpg", isBestSeller: true },
  { id: 9, title: "Game 7", price: 45, description: "Casual game", category: "game", image: "/images/game/game7.jpg" },
  { id: 10, title: "Headphone 7", price: 170, description: "Over-ear premium", category: "headphone", image: "/images/headphone/headphone7.jpg" },
  { id: 11, title: "Laptop 5", price: 2000, description: "Premium ultrabook", category: "laptop", image: "/images/laptop/laptop5.jpg" },
  { id: 12, title: "Headphone 8", price: 110, description: "Good bass", category: "headphone", image: "/images/headphone/headphone8.jpg" },
  { id: 13, title: "Game 10", price: 50, description: "Indie game", category: "game", image: "/images/game/game10.jpg" },
  { id: 14, title: "Laptop Pro 14", price: 2500, description: "Professional laptop for designers", category: "laptop", image: "/images/laptop/laptop1.jpg", isBestSeller: true },
  { id: 15, title: "Laptop Air 13", price: 1400, description: "Ultra-thin and lightweight", category: "laptop", image: "/images/laptop/laptop2.jpg" },
  { id: 16, title: "Laptop Gaming 15", price: 2200, description: "High-end gaming laptop", category: "laptop", image: "/images/laptop/laptop3.jpg", isBestSeller: true },
  { id: 17, title: "Laptop Business 14", price: 1600, description: "Perfect for business professionals", category: "laptop", image: "/images/laptop/laptop5.jpg" },
  { id: 18, title: "Laptop Creator 16", price: 2800, description: "Video editing powerhouse", category: "laptop", image: "/images/laptop/laptop1.jpg" },

  // موبایل‌ها (15 محصول)
  { id: 19, title: "Mobile 1", price: 800, description: "Latest flagship phone", category: "mobile", image: "/images/mobile/mobile1.jpg", isBestSeller: true },
  { id: 20, title: "Mobile 2", price: 650, description: "Budget-friendly smartphone", category: "mobile", image: "/images/mobile/mobile2.jpg" },
  { id: 21, title: "Mobile 5", price: 900, description: "Premium display phone", category: "mobile", image: "/images/mobile/mobile3.jpg", isBestSeller: true },
  { id: 22, title: "Mobile 6", price: 550, description: "Entry-level smartphone", category: "mobile", image: "/images/mobile/mobile4.jpg" },
  { id: 23, title: "Mobile 7", price: 1100, description: "High zoom camera phone", category: "mobile", image: "/images/mobile/mobile2.jpg", isBestSeller: true },
  { id: 24, title: "Mobile 9", price: 950, description: "Gaming mobile phone", category: "mobile", image: "/images/mobile/mobile3.jpg", isBestSeller: true },
  { id: 25, title: "Mobile 10", price: 700, description: "Fast charging phone", category: "mobile", image: "/images/mobile/mobile4.jpg" },
  { id: 26, title: "Mobile Pro Max", price: 1200, description: "Largest screen phone", category: "mobile", image: "/images/mobile/mobile1.jpg", isBestSeller: true },
  { id: 27, title: "Mobile Mini", price: 500, description: "Compact phone design", category: "mobile", image: "/images/mobile/mobile2.jpg" },
  { id: 28, title: "Mobile Ultra", price: 1300, description: "Most advanced features", category: "mobile", image: "/images/mobile/mobile3.jpg", isBestSeller: true },
  { id: 29, title: "Mobile Lite", price: 450, description: "Simple and reliable", category: "mobile", image: "/images/mobile/mobile4.jpg" },
  { id: 30, title: "Mobile Plus", price: 850, description: "Enhanced performance", category: "mobile", image: "/images/mobile/mobile1.jpg" },
  { id: 31, title: "Mobile Max", price: 1400, description: "Maximum battery life", category: "mobile", image: "/images/mobile/mobile2.jpg", isBestSeller: true },
  { id: 32, title: "Mobile Focus", price: 750, description: "Perfect photography phone", category: "mobile", image: "/images/mobile/mobile3.jpg" },
  { id: 33, title: "Mobile Speed", price: 900, description: "Fastest processor", category: "mobile", image: "/images/mobile/mobile4.jpg", isBestSeller: true },

  // هدفون‌ها (15 محصول)
  { id: 34, title: "Headphone 1", price: 150, description: "Budget wireless headphones", category: "headphone", image: "/images/headphone/headphone1.jpg" },
  { id: 35, title: "Headphone 2", price: 200, description: "Noise-canceling headphones", category: "headphone", image: "/images/headphone/headphone2.jpg", isBestSeller: true },
  { id: 36, title: "Headphone 3", price: 180, description: "Sports headphones", category: "headphone", image: "/images/headphone/headphone3.jpg" },
  { id: 37, title: "Headphone 4", price: 220, description: "Premium sound quality", category: "headphone", image: "/images/headphone/headphone7.jpg", isBestSeller: true },
  { id: 38, title: "Headphone 5", price: 130, description: "Lightweight earbuds", category: "headphone", image: "/images/headphone/headphone8.jpg" },
  { id: 39, title: "Headphone 6", price: 250, description: "Studio-grade headphones", category: "headphone", image: "/images/headphone/headphone10.jpg", isBestSeller: true },
  { id: 40, title: "Headphone 9", price: 190, description: "Long battery life", category: "headphone", image: "/images/headphone/headphone2.jpg" },
  { id: 41, title: "Headphone 11", price: 280, description: "Wireless charging case", category: "headphone", image: "/images/headphone/headphone3.jpg", isBestSeller: true },
  { id: 42, title: "Headphone 12", price: 160, description: "Water-resistant earbuds", category: "headphone", image: "/images/headphone/headphone7.jpg" },
  { id: 43, title: "Headphone 13", price: 240, description: "Gaming headphones with mic", category: "headphone", image: "/images/headphone/headphone8.jpg", isBestSeller: true },
  { id: 44, title: "Headphone 14", price: 170, description: "Comfort fit design", category: "headphone", image: "/images/headphone/headphone10.jpg" },
  { id: 45, title: "Headphone 15", price: 300, description: "Best sound quality", category: "headphone", image: "/images/headphone/headphone1.jpg", isBestSeller: true },
  { id: 46, title: "Headphone 16", price: 140, description: "Foldable design", category: "headphone", image: "/images/headphone/headphone2.jpg" },
  { id: 47, title: "Headphone 17", price: 210, description: "App-controlled EQ", category: "headphone", image: "/images/headphone/headphone3.jpg" },
  { id: 48, title: "Headphone 18", price: 260, description: "360 surround sound", category: "headphone", image: "/images/headphone/headphone7.jpg", isBestSeller: true },

  // گجت‌ها و بازی‌ها (15 محصول)
  { id: 49, title: "Game 1", price: 30, description: "Adventure game", category: "game", image: "/images/game/game1.jpg" },
  { id: 50, title: "Game 2", price: 35, description: "Action game", category: "game", image: "/images/game/game1.jpg", isBestSeller: true },
  { id: 51, title: "Game 3", price: 25, description: "Puzzle game", category: "game", image: "/images/game/game1.jpg" },
  { id: 52, title: "Game 4", price: 40, description: "Sports game", category: "game", image: "/images/game/game1.jpg", isBestSeller: true },
  { id: 53, title: "Game 5", price: 45, description: "RPG game", category: "game", image: "/images/game/game1.jpg" },
  { id: 54, title: "Game 6", price: 55, description: "Strategy game", category: "game", image: "/images/game/game1.jpg", isBestSeller: true },
  { id: 55, title: "Game 8", price: 38, description: "Racing game", category: "game", image: "/images/game/game1.jpg" },
  { id: 56, title: "Game 9", price: 42, description: "Shooting game", category: "game", image: "/images/game/game1.jpg", isBestSeller: true },
  { id: 57, title: "Smart Watch Pro", price: 280, description: "Advanced fitness tracking", category: "game", image: "/images/game/game1.jpg", isBestSeller: true },
  { id: 58, title: "Smart Band", price: 60, description: "Budget fitness tracker", category: "game", image: "/images/game/game1.jpg" },
  { id: 59, title: "Portable Speaker", price: 120, description: "Waterproof speaker", category: "game", image: "/images/game/game1.jpg", isBestSeller: true },
  { id: 60, title: "Power Bank", price: 50, description: "High capacity charger", category: "game", image: "/images/game/game1.jpg" },
  { id: 61, title: "USB Hub", price: 35, description: "Multi-port connectivity", category: "game", image: "/images/game/game1.jpg" },
  { id: 62, title: "Phone Stand", price: 20, description: "Adjustable mount", category: "game", image: "/images/game/game1.jpg" },
  { id: 63, title: "Charging Cable", price: 25, description: "Fast charging cable", category: "game", image: "/images/game/game1.jpg", isBestSeller: true },
];
